export const TURKISH_AIRPORTS = [
    { id: 'IST', city: 'İstanbul', name: 'İstanbul Havalimanı', code: 'IST' },
    { id: 'SAW', city: 'İstanbul', name: 'Sabiha Gökçen Havalimanı', code: 'SAW' },
    { id: 'ESB', city: 'Ankara', name: 'Esenboğa Havalimanı', code: 'ESB' },
    { id: 'ADB', city: 'İzmir', name: 'Adnan Menderes Havalimanı', code: 'ADB' },
    { id: 'AYT', city: 'Antalya', name: 'Antalya Havalimanı', code: 'AYT' },
    { id: 'GZP', city: 'Antalya', name: 'Gazipaşa Havalimanı', code: 'GZP' },
    { id: 'ADA', city: 'Adana', name: 'Adana Şakirpaşa Havalimanı', code: 'ADA' },
    { id: 'DLM', city: 'Muğla', name: 'Dalaman Havalimanı', code: 'DLM' },
    { id: 'BJV', city: 'Muğla', name: 'Milas-Bodrum Havalimanı', code: 'BJV' },
    { id: 'TZX', city: 'Trabzon', name: 'Trabzon Havalimanı', code: 'TZX' },
    { id: 'GZT', city: 'Gaziantep', name: 'Gaziantep Havalimanı', code: 'GZT' },
    { id: 'ASR', city: 'Kayseri', name: 'Kayseri Havalimanı', code: 'ASR' },
    { id: 'SZF', city: 'Samsun', name: 'Çarşamba Havalimanı', code: 'SZF' },
    { id: 'VAN', city: 'Van', name: 'Ferit Melen Havalimanı', code: 'VAN' },
    { id: 'ERZ', city: 'Erzurum', name: 'Erzurum Havalimanı', code: 'ERZ' },
    { id: 'KYA', city: 'Konya', name: 'Konya Havalimanı', code: 'KYA' },
    { id: 'MLX', city: 'Malatya', name: 'Erhama Havalimanı', code: 'MLX' },
    { id: 'DIY', city: 'Diyarbakır', name: 'Diyarbakır Havalimanı', code: 'DIY' },
    { id: 'EZS', city: 'Elazığ', name: 'Elazığ Havalimanı', code: 'EZS' },
    { id: 'HTY', city: 'Hatay', name: 'Hatay Havalimanı', code: 'HTY' },
    { id: 'VAS', city: 'Sivas', name: 'Sivas Nuri Demirağ Havalimanı', code: 'VAS' },
    { id: 'GNY', city: 'Şanlıurfa', name: 'GAP Havalimanı', code: 'GNY' },
    { id: 'EDO', city: 'Balıkesir', name: 'Koca Seyit Havalimanı', code: 'EDO' },
    { id: 'DNZ', city: 'Denizli', name: 'Çardak Havalimanı', code: 'DNZ' },
    { id: 'ISE', city: 'Isparta', name: 'Süleyman Demirel Havalimanı', code: 'ISE' },
];
